[package]
name = "rust-nbc"
version = "0.1.0"
authors = ["Gökberk Koçak <gk34@st-andrews.ac.uk>"]
edition = "2018"

[build-dependencies]
bindgen = "0.52.0"
cc = { version = "1.0.37", features = ["parallel"] } 

[features]
generate-bindings = [] # feature has no explicit dependencies